### ISSUE TITLE
Double Unlocking "Fresh" Vaults (1.0.1)

### ISSUE THREAD

**Issue by Dynant** [DTanJP/Spigot-ForgetfulTrialVault#3]
Used Version: 1.0.1
Delay: 10 sec

When a vault has not be used yet it's possible to unlock it two times by double clicking. See video: https://youtu.be/-drwhzNm51E

**Comment by DTanJP** [comment]
Released version 1.0.3. Please let me know if there are any more bugs or if the issue still persists.
Thank you for the heads up! Your YouTube video was very helpful on understanding the issue.

**Comment by Dynant** [comment]
Hey, Thanks for fixing it so quickly, unfortunately i cannot test it on our server because we use paper which still has 1.21.5 as experimental. Is it possible to release it with version 1.21.4? I also noticed the version in `plugin.yml` is still version: 1.0.2.

**Comment by DTanJP** [comment]
Hello Dynant,

Thanks for catching that! I released a backported version of 1.0.3 as 1.0.15 to support Minecraft 1.21.4
Please check out my bin directory of my repo here:
https://github.com/DTanJP/Spigot-ForgetfulTrialVault/tree/main/bin

I tested it on 1.21.4 using RTag 1.5.10

Let me know if you think the issue still persists or if there are any more bugs you found.

**Comment by Dynant** [comment]
Tested with version 1.0.15 and issue is still there. It can be easily recreated with these steps:

- run command: `/ftv reset 10000`
- Unlock a vault
- Wait 10 seconds
- Reload plugins using command: `/reload confirm`

You will notice that the vault will show the "animation" again when nearby and can be unlocked twice by double clicking. The `Vaults.dat` file does have the timestamp for the location + user. 

When I test this with a longer reset delay and reload while delay is still "active" it will not allow this.

Also noticed the language for the time is not working:
![Image](https://github.com/user-attachments/assets/a1c29b42-ac03-49e7-ae94-7ccba55387d0)

**Comment by DTanJP** [comment]
Hello Dynant,

I have replace v1.0.15 in the bin directory. Please redownload and try again and let me know if the issue still persists.

I tried:
/ftv locale espanol
/ftv locale english
Both of them seems to be working.
Please check again or let me know the steps taken.

![Image](https://github.com/user-attachments/assets/0a9a35f5-a0c6-49ce-b494-10edcb266159)

**Comment by Dynant** [comment]
Thanks for the update. I still encounter the same issue. When a timer has expired and I reload plugins or restart the server i can double unlock it. When you are standing next to the vault it will also do the unlock animation after the plugins have been reloaded, almost feels like the vault has forgot the player ever unlocked  when the plugin is unloaded/loaded

I see the language is working correctly, only noticed the English time strings are in capitals that was throwing me off
![Image](https://github.com/user-attachments/assets/b37d6e50-afac-4c39-80e2-e1cc0f87f0dd)

**Comment by DTanJP** [comment]
Hello Dynant,

Thank you for your patience. I suspect the bug might have been from the loading method from the plugin. I modified the load method then tested the new 1.0.15 plugin several times by reloading several times via ingame command and console and I even restarted the server several times. I even deleted the world save file and plugin and started from new again and tried reloading several times again afterwards. I wasn't able to replicate the double reset bug anymore. Please try re-downloading the 1.0.15 jar again and let me know if the double reset bug still persists.

Regarding the locale, yea it bothered me too, I reverted it back to Letter case again.

**Comment by Dynant** [comment]
Hey,
Thanks for the fix. It seems to work correctly now. I also tested multiple use cases and I wasn't able to double reset anymore. I think the issue can be closed now and I will let you know if I find any other issues. 

You probably want to also apply the fix to the version 1.0.3 as well right?

**Comment by DTanJP** [comment]
Hello Dynant,

Thank you for checking and confirming. Yes I will also be applying the fix to 1.0.3 as well.
Just didn't want to keep exporting 2 jar everytime during testing.
